apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
data:
  config: |
    nonMasqueradeCIDRs:
      - 10.32.0.0/14    # Cluster pod IP range
    masqLinkLocal: false
    resyncInterval: 60s