apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service_name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service_name }}
    spec:
      {{- if .Values.service_account.enabled }}
      serviceAccountName: {{ .Values.service_account.name }}
      {{- end }}
      containers:
        - name: {{ .Values.service_name }}
          image: "{{ .Values.deployment.container.image }}:{{ .Values.deployment.container.app_version }}"
          {{- if .Values.external_secrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.service_name }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
          resources:
            requests:
              memory: {{ .Values.deployment.container.resources.requests.memory }}
              cpu: {{ .Values.deployment.container.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.container.resources.limits.memory }}
              cpu: {{ .Values.deployment.container.resources.limits.cpu }}