apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service_name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service_name }}
    spec:
      containers:
        - name: {{ .Values.service_name }}
          image: {{ .Values.deployment.container.image }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}