apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service_name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service_name }}
    spec:
      {{- if and .Values.service_account.enabled }}
      serviceAccountName: {{ .Values.service_account.enabled }}
      {{- end }}
      containers:
        - name: {{ .Values.service_name }}
          image: "{{ .Values.deployment.container.image }}:{{ .Values.deployment.container.app_version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.deployment.container.port }}