{{- if .Values.external_secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.service_name }}
spec:
  refreshInterval: {{ .Values.external_secrets.refreshInterval }}        
  secretStoreRef:
    kind: {{ .Values.external_secrets.secret_store_ref.kind }}
    name: {{ .Values.external_secrets.secret_store_ref.name }}
  target:
    name:  {{ .Values.service_name }}
    creationPolicy: Owner
  {{- if .Values.external_secrets.keys }}
  data:
    {{- range .Values.external_secrets.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: "{{ $.Values.external_secrets.prefix }}-{{ . }}"
    {{- end }}
  {{- end }}
  {{- if .Values.external_secrets.regex }}
  dataFrom:
    - find:
        name:
          regexp: {{ .Values.external_secrets.regex.find }}
        transform:
          - type: "rename"
            regex:
              pattern: {{ .Values.external_secrets.regex.pattern }}
              replacement: "$1"
  {{- end }}
{{- end }}