{{- if .Values.service_account.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ .Values.service_account.name }}
  {{- with .Values.service_account.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}