apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
spec:
  selector:
    app: {{ .Values.service_name }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.container.port }}
      targetPort: {{ .Values.deployment.container.port }}
