service_name: example-api

deployment:
  replicas: 1
  container:
    image: nginx
    app_version: stable
    port: 80
    resources:
      limits:
        cpu: 100m
        memory: 15Mi
      requests:
        cpu: 100m
        memory: 15Mi

external_secrets:
  enabled: false
  refreshInterval: 1m

ingress:
  enabled: false

service_account:
  enabled: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  metrics:
    cpuUtilization: 70
    memoryUtilization: 80
  behavior:
    scaleDown:
      value: 1
    scaleUp:
      value: 5