service_name: example-api

deployment:
  replicas: 1
  container:
    image: nginx
    app_version: stable
    port: 80

external_secrets:
  enabled: false

ingress:
  enabled: false

service_account:
  enabled: false