service_name: example-api

deployment:
  replicas: 1
  container:
    image: nginx
    app_version: stable
    port: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"

external_secrets:
  enabled: false
  refreshInterval: 1m

ingress:
  enabled: false

service_account:
  enabled: false

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  metrics:
    cpuUtilization: 70
    memoryUtilization: 80
  behavior:
    scaleDown:
      value: 1
    scaleUp:
      value: 50